package main

import (
	"testing"

	"github.com/doozr/euler.go/euler"
)

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.


Answer:
    4613732
*/

func SumFibEvens(limit int) int {
	ch := make(chan int)
	total := 0
	go math.Fib(ch)
	for next := <-ch; next < limit; next = <-ch {
		if next%2 == 0 {
			total += next
		}
	}
	return total
}

func TestProblem0002FibonacciSequence(t *testing.T) {
	total := SumFibEvens(4000000)
	expected := 4613732
	if total != expected {
		t.Errorf("Expected %d, received %d", expected, total)
	}
}
